import {chromium} from '/tmp/cez160-webkit/node_modules/playwright/index.mjs';
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';import {spawn,execFileSync} from 'node:child_process';
import assert from 'node:assert/strict';
const out='.ai/qa/runtime-verified/target-drilldown-audit',root='/tmp/fc764-subagent-replay';mkdirSync(root+'/.ai/cezar/runs',{recursive:true});mkdirSync(root+'/home',{recursive:true});
const run=JSON.parse(readFileSync('packages/web/e2e/fixtures/subagents-run.record.json'));writeFileSync(root+'/.ai/cezar/runs.json',JSON.stringify([run]));const recorded=readFileSync('packages/web/e2e/fixtures/subagents-run.ndjson','utf8').trim().split('\n').map(JSON.parse);const index=recorded.findIndex(e=>e.type==='item.completed'&&e.item?.id==='toolu_task_a_1');recorded.splice(index,0,...Array.from({length:34},(_,i)=>({type:'item.completed',item:{kind:'tool',id:'toolu_sub_long_'+i,name:'Bash',toolKind:'execute',title:'Ran long check '+(i+1),status:'completed',output:'long check '+(i+1)+' passed',exitCode:0,parentItemId:'toolu_task_a_1'},stepId:'task'})));writeFileSync(root+'/.ai/cezar/runs/'+run.id+'.ndjson',recorded.map((e,i)=>JSON.stringify({...e,seq:i+1,ts:new Date(Date.UTC(2026,6,21,10,0,i)).toISOString()})).join('\n')+'\n');
const server=spawn(process.execPath,['/tmp/fc764-final-integrated/packages/cezar/dist/index.js','serve','--repo',root,'--port','44865','--no-open'],{env:{...process.env,CEZ_HOME:root+'/home',CEZ_DRY_RUN:'1',CEZ_SKILLS_AUTO_UPDATE:'0'},stdio:'ignore'});
const b=await chromium.launch({headless:true,executablePath:'/home/agent/.cache/ms-playwright/chromium-1234/chrome-linux64/chrome',args:['--no-sandbox']});let results=[];
try{for(let i=0;i<60;i++){try{if((await fetch('http://127.0.0.1:44865/api/v1/health')).ok)break}catch{}await new Promise(r=>setTimeout(r,100));}
const page=await b.newPage({viewport:{width:1440,height:900}});page.on('pageerror',e=>results.push({error:String(e)}));
for(const method of ['pointer','keyboard']){await page.goto('http://127.0.0.1:44865/tasks/'+run.id);const dock=page.locator('[data-slot="agents-dock"] > button');await dock.waitFor();await dock.click();const row=page.locator('[data-slot="agent-item"]:nth-of-type(2) button');await row.waitFor();await row.scrollIntoViewIfNeeded();const before=await row.boundingBox();if(method==='pointer')await row.click();else{await row.focus();await page.keyboard.press('Enter');}await page.waitForTimeout(800);const sheet=page.locator('[data-slot="subagent-sheet"]');const opened=await sheet.count();results.push({method,before,opened,dialogCount:await page.getByRole('dialog').count(),text:opened?await sheet.innerText():null});await page.screenshot({path:out+'/drilldown-'+method+'.png'});if(opened)await page.keyboard.press('Escape');}
const ab=(...args)=>JSON.parse(execFileSync('/tmp/cez-e2e-86/agent-browser',['--session','fc764-drilldown-harness',...args,'--json'],{encoding:'utf8',timeout:45000}));
try { ab('set','viewport','1440','900');ab('open','http://127.0.0.1:44865/tasks/'+run.id);ab('wait','--fn',`document.querySelector('[data-slot="agents-dock"] > button') !== null`);ab('click','[data-slot="agents-dock"] > button');ab('wait','--fn',`document.querySelectorAll('[data-slot="agent-item"]').length === 2`);ab('click','[data-slot="agent-item"]:nth-of-type(2) button');results.push({method:'agent-browser',observation:ab('eval',`({opened:!!document.querySelector('[data-slot="subagent-sheet"]'),text:document.querySelector('[data-slot="subagent-sheet"]')?.textContent})`)}); } catch(e){results.push({method:'agent-browser',error:String(e)});}finally{ab('close');}
writeFileSync(out+'/drilldown.json',JSON.stringify(results,null,2));console.log(JSON.stringify(results));}finally{await b.close();server.kill();}
