#!/usr/bin/env node
// Copy the repo's README into this package before it is built/packed.
//
// There is exactly one README (the repo root's): it is the project's GitHub front page AND the
// npm page for `@wjarka/cezarion`, and those must not be allowed to drift into two documents
// saying different things about the same tool. `files` can only reference paths inside the
// package, so the one source is copied in rather than referenced out — the copy is gitignored,
// regenerated by every build, and never edited by hand.
//
// Runs as `prebuild`, so `npm run build` (and the release pipeline, which builds first) always
// packs a current copy. `check:pack` is the gate that notices if this ever stops happening.

import { copyFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const packageRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const repoRoot = path.resolve(packageRoot, '../..');

copyFileSync(path.join(repoRoot, 'README.md'), path.join(packageRoot, 'README.md'));
