import {readFileSync,writeFileSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
import {resolve} from 'node:path';
const runtime=resolve('.ai/qa/runtime-verified'),out=resolve('.ai/qa/settings');
const proof=JSON.parse(readFileSync(runtime+'/server-proof.json'));
const run=(...args)=>execFileSync(runtime+'/browser.sh',args,{encoding:'utf8',env:{...process.env,RUNTIME_BROWSER_SESSION:'settings-579'}});
const evaluate=code=>JSON.parse(JSON.parse(run('eval',`JSON.stringify(${code})`)));
const checks=[];
run('set','viewport','390','844','2');run('open',proof.baseUrl+'/p/default/settings');run('wait','700');
run('click','.settings-section-picker summary');run('click','[data-slot="settings-nav-mobile"] [data-section="agents"]');run('wait','500');
if(!evaluate(`location.pathname.endsWith('/settings/agents')&&!document.querySelector('.settings-section-picker').open`))throw Error('Mobile scoped navigation failed');checks.push('Mobile disclosure navigates to scoped Agents and closes.');
run('open',proof.baseUrl+'/p/default/settings/agent-config');run('wait','700');
run('eval',`[...document.querySelectorAll('[data-slot="agent-config-shortcut"]')].find(b=>b.textContent.includes('MCP config')).click()`);run('wait','400');
const path=proof.repo+'/.mcp.json',original=readFileSync(path,'utf8');
const draft=JSON.stringify({...JSON.parse(original),fixtureSmoke:true},null,2);
run('fill','[data-slot="code-editor-input"]',draft);
run('find','role','button','click','--name','Reset','--exact');
if(evaluate(`document.querySelector('[data-slot="code-editor-input"]').value`)!==original)throw Error('Reset did not restore loaded MCP file');
checks.push('MCP editor Reset restores loaded project file without writing.');
run('fill','[data-slot="code-editor-input"]',draft);run('find','role','button','click','--name','Save file','--exact');run('wait','600');
if(!JSON.parse(readFileSync(path,'utf8')).fixtureSmoke)throw Error('MCP Save did not reach actual file');
run('fill','[data-slot="code-editor-input"]',original);run('find','role','button','click','--name','Save file','--exact');run('wait','600');
if(readFileSync(path,'utf8')!==original)throw Error('MCP fixture restoration failed');
checks.push('MCP Save writes the real project file through the versioned API; original fixture content restored through Save.');
run('open',proof.baseUrl+'/settings/global/projects');run('wait','600');
run('click','[data-slot="projects-section"] > button');run('wait','500');
if(!evaluate(`!!document.querySelector('[role="dialog"]')`))throw Error('Add project dialog absent');
checks.push('Settings Add project opens the existing real project-registration dialog.');
run('screenshot',out+'/add-project-dialog.png');run('press','Escape');
writeFileSync(out+'/smoke-proof.json',JSON.stringify({sourceCommit:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),baseUrl:proof.baseUrl,checkedAt:new Date().toISOString(),checks,disclosure:'No account authentication, notifications, MCP execution, skill updates, task launches or project removal. File writes stayed in the isolated fixture.'},null,2));
console.log(checks.join('\n'));
