import {chromium} from '/tmp/cez160-webkit/node_modules/playwright/index.mjs';
import {readFileSync,writeFileSync} from 'node:fs';
import {runRecordSchema,githubRefStatusDataSchema} from '../../../../../packages/cezar/dist/contract/index.js';
const out='.ai/qa/runtime-verified/independent-review/shell',base='http://127.0.0.1:44864';
const original=JSON.parse(readFileSync(out+'/repos/iac/.ai/cezar/runs.json'))[0];
const states=['queued','running','waiting','review','done','failed','cancelled','monitoring'];
const runs=states.map((status,i)=>runRecordSchema.parse({...original,id:`20000000-0000-4000-8000-00000000000${i}`,title:'Status: '+status,status:status==='monitoring'?'running':status,activity:status==='monitoring'?'monitoring':undefined,delegation:undefined,parentRunId:undefined,groupId:undefined,pinned:false,seenAt:new Date(Date.now()+100000).toISOString(),referencedIssueUrl:undefined,pullRequestUrl:undefined}));
runs.push(...['A','B'].map((variant,i)=>runRecordSchema.parse({...original,id:`20000000-0000-4000-8000-00000000001${i}`,title:'Grouped comparison',status:'done',delegation:undefined,parentRunId:undefined,pullRequestUrl:undefined,referencedIssueUrl:undefined,pinned:false,groupId:'fixture-variants',variant,seenAt:new Date(Date.now()+100000).toISOString()})));
const browser=await chromium.launch({headless:true,executablePath:'/home/agent/.cache/ms-playwright/chromium-1234/chrome-linux64/chrome',args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1440,height:1400},reducedMotion:'reduce'});
await page.route('**/api/v1/**',r=>{const u=new URL(r.request().url());if(u.pathname.endsWith('/github/ref-status'))return r.fulfill({json:references});if(/\/runs$/.test(u.pathname))return r.fulfill({json:runs});return r.continue();});
const references=githubRefStatusDataSchema.parse({available:true,prs:Object.fromEntries(['draft','review-required','changes-requested','checks-pending','checks-failing','ready','merged','closed'].map((s,i)=>[i+1,s])),issues:{101:'open',102:'completed',103:'not-planned'},recheckAfterMs:null});
const proof=[];
for(const theme of ['light','dark']){await page.addInitScript(theme=>{localStorage.setItem('cez-theme',theme);localStorage.setItem('cez-sidebar-collapsed',JSON.stringify({website:true,earwitness:true}));},theme);await page.goto(base+'/p/iac/skills');await page.waitForTimeout(700);await page.screenshot({path:out+'/statuses-'+theme+'.png'});proof.push({theme,reference:theme==='light'?'T2fE7':'L61J13',states:await page.locator('[data-slot="task-row"]').evaluateAll(rows=>rows.map(row=>({title:row.textContent,status:row.querySelector('[data-slot="status-dot"]')?.getAttribute('aria-label'),color:getComputedStyle(row.querySelector('[data-slot="status-dot"]')).backgroundColor})))});}
for(let i=0;i<8;i++){runs[i].pullRequestUrl='https://github.com/hearsay-tools/cezarion/pull/'+(i+1);if(i<3)runs[i].referencedIssueUrl='https://github.com/hearsay-tools/cezarion/issues/'+(i+101);}
for(const theme of ['light','dark']){await page.addInitScript(t=>localStorage.setItem('cez-theme',t),theme);await page.reload();await page.waitForTimeout(700);await page.screenshot({path:out+'/reference-statuses-'+theme+'.png'});}
await page.locator('[data-slot=group-tile]').click(); await page.waitForTimeout(200); await page.screenshot({path:out+'/variant-group-expanded.png'}); proof.push({groupExpanded:await page.locator('[data-slot=group-compare]').count(),compareHref:await page.locator('[data-slot=group-compare]').getAttribute('href')});
writeFileSync(out+'/statuses.json',JSON.stringify({fixture:runs,proof},null,2));await browser.close();
