import {execFileSync} from 'node:child_process';import {readFileSync,writeFileSync} from 'node:fs';import {resolve} from 'node:path';import * as C from '../../../packages/cezar/dist/contract/index.js';
const qa=resolve('.ai/qa/runtime-verified'),out=resolve('.ai/qa/iteration-3'),base=JSON.parse(readFileSync(qa+'/server-proof.json')).baseUrl;
const cli=(...args)=>execFileSync(qa+'/browser.sh',args,{env:{...process.env,RUNTIME_BROWSER_SESSION:'runtime-tools-isolated'},encoding:'utf8',maxBuffer:8e6}).trim();
const health=C.healthResponseSchema.parse(await(await fetch(base+'/api/v1/health')).json());health.repo={root:'~/code/cezar',branch:'main',remote:'https://github.com/apptension/cezar'};health.repoRoot='~/code/cezar';health.checks=[{name:'git',available:true,version:'Ready'},{name:'gh',available:true,version:'Authenticated'},{name:'codex',available:true,version:'Provider connected'},{name:'claude',available:true,version:'Ready'}];C.healthResponseSchema.parse(health);
const browse=C.fsBrowseResponseSchema.parse({path:'/fixture/projects',parent:null,dirs:[{name:'cezar',path:'/fixture/projects/cezar',isRepo:true},{name:'notes',path:'/fixture/projects/notes',isRepo:false}],truncated:false});
cli('--init-script',out+'/block-live-health.js','open',base+'/tools');cli('network','route',base+'/api/v1/health','--body',JSON.stringify(health));cli('network','route',base+'/api/v1/fs/browse*','--body',JSON.stringify(browse));
for(const theme of ['light','dark']){
 cli('set','viewport','1440','1120');cli('eval',`localStorage.setItem('cez-theme','${theme}');localStorage.setItem('cez-sidebar-width','264');location.reload()`);cli('wait','650');cli('eval','document.activeElement?.blur()');cli('screenshot',out+'/tools-matched-'+theme+'.png');
 const observed=cli('eval',`JSON.stringify({text:document.querySelector('[data-route="workspace-tools"]').innerText,styles:[...document.querySelectorAll('[data-route="workspace-tools"] h1,[data-route="workspace-tools"] h2,[data-route="workspace-tools"] button')].map(e=>{const s=getComputedStyle(e),r=e.getBoundingClientRect();return {text:e.textContent,font:s.fontFamily,size:s.fontSize,weight:s.fontWeight,lineHeight:s.lineHeight,width:r.width,height:r.height}})})`);const parsed=JSON.parse(JSON.parse(observed));if(!parsed.text.includes('Provider connected')||!parsed.text.includes('github.com/apptension/cezar'))throw Error('Health fixture not rendered');writeFileSync(out+'/tools-matched-'+theme+'.json',JSON.stringify(parsed,null,2));
}
cli('eval',`Array.from(document.querySelectorAll('button')).find(x=>x.textContent==='Open local folder').click()`);cli('wait','500');cli('screenshot',out+'/tools-local-fixture.png');cli('press','Escape');cli('eval',`Array.from(document.querySelectorAll('button')).find(x=>x.textContent==='Clone from GitHub').click()`);cli('wait','300');cli('screenshot',out+'/tools-clone-fixture.png');
writeFileSync(out+'/tools-fixture-disclosure.json',JSON.stringify({disclosure:'Browser-only schema-validated health and folder-list fixtures. No clone or project registration executed. Four enum-valid tool rows analogous to design; existing runtime format retained. Readiness/version strings are fixture data, not actual probes.',health,browse},null,2));console.log('Captured light/dark Tools with264pxsidebar, and isolated-folder/clone dialogs.');
