import {existsSync,mkdirSync,readFileSync,writeFileSync,copyFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {execFileSync,spawn} from 'node:child_process';
import {createHash} from 'node:crypto';
const source=resolve(process.argv[2]??'.');
const qa=resolve(source,'.ai/qa/runtime-verified');
const repo=resolve(qa,'fixture-repo');
mkdirSync(repo+'/.ai/cezar/runs',{recursive:true});
const git=(...a)=>execFileSync('git',['-C',repo,...a]);
if(!existsSync(repo+'/.git')){git('init','-q','-b','main');git('config','user.email','fixture@example.test');git('config','user.name','QA Fixture');writeFileSync(repo+'/README.md','# Cezarion fixture\n');git('add','.');git('commit','-qm','Initialize fixture');git('branch','feature/runtime-audit');}
writeFileSync(repo+'/README.md','# Cezarion fixture\n\nA populated working tree for visual verification.\n');
const record=JSON.parse(readFileSync(source+'/packages/web/e2e/fixtures/thread-run.record.json'));
const runs=['session','worker','review','variant'].map((name,i)=>({...record,id:'fixture-'+name,title:['Improve session navigation','Review keyboard controls','Polish task overview','Compare compact layout'][i],titleSummary:undefined,status:i===2?'review':'done',groupId:i===0||i===3?'fixture-group':undefined,variant:i===0?'A':i===3?'B':undefined,parentRunId:i===1?'fixture-session':undefined,archived:false,worktreePath:repo,branch:'main',createdAt:new Date(Date.now()-i*3600000).toISOString(),startedAt:new Date(Date.now()-i*3600000).toISOString(),inputTokens:42000,outputTokens:6000,costUsd:0.42,peakRssBytes:440401920,diffStat:{adds:12,dels:3,files:1}}));
writeFileSync(repo+'/.ai/cezar/runs.json',JSON.stringify(runs));
for(const run of runs)copyFileSync(source+'/packages/web/e2e/fixtures/thread-run.ndjson',repo+'/.ai/cezar/runs/'+run.id+'.ndjson');
writeFileSync(repo+'/.ai/cezar/todos.json',JSON.stringify([{id:'follow-up',summary:'Validate populated task views on desktop and mobile.',suggestedPrompt:'Check all task views.',runnable:true,taskId:'fixture-session'}]));
const port=process.argv[3]??'44629';
const env={PATH:process.env.PATH,CEZ_HOME:qa+'/cez-home',CEZ_DRY_RUN:'1',CEZ_FOLLOWUPS:'1',CEZ_AUTOMATIONS:'1',CEZ_SKILLS_AUTO_UPDATE:'0',CEZ_SINGLE_PROJECT:'1'};
const entry=source+'/packages/cezar/dist/index.js';
const child=spawn(process.execPath,[entry,'serve','--repo',repo,'--port',port,'--no-open'],{env,stdio:'inherit'});
const hash=p=>createHash('sha256').update(readFileSync(p)).digest('hex');
writeFileSync(qa+'/server-proof.json',JSON.stringify({source,sourceCommit:execFileSync('git',['-C',source,'rev-parse','HEAD'],{encoding:'utf8'}).trim(),entry,entrySha256:hash(entry),webRoot:source+'/packages/cezar/web/dist',indexSha256:hash(source+'/packages/cezar/web/dist/index.html'),pid:child.pid,repo,cezHome:env.CEZ_HOME,baseUrl:'http://127.0.0.1:'+port,startedAt:new Date().toISOString(),credentials:'Child receives only PATH and explicit CEZ fixture flags; no inherited credentials'},null,2));
child.on('exit',c=>process.exit(c??0));
